[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blosum"
version = "2.2.0"
description = "A simple BLOSUM toolbox without dependencies."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPL-3.0"}
keywords = ["BLOSUM", "reader", "bio", "bioinformatics", "blosum62", "blosum45", "blosum50", "blosum90"]
authors = [
    {name = "Jules Kreuer / not_a_feature"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/not-a-feature/blosum"
Repository = "https://github.com/not-a-feature/blosum"

[project.optional-dependencies]
dev = [
    "pytest>=6.2",
    "pytest-cov>=2.12",
    "mypy>=0.910",
    "tox>=3.24",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
blosum = ["py.typed"]

[tool.pytest.ini_options]
addopts = "--cov=blosum"
testpaths = [
    "tests",
]
xfail_strict = true

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
